---
- name: Clone LXC containers from a reference container
  hosts: all
  become: yes
  vars:
    container_names:
      - server1
      - server2
      - server3
      - server4
      - server5
  tasks:
    - name: Ensure LXC is installed
      apt:
        name: lxc
        state: present

    - name: Clone LXC containers
      loop: "{{ container_names }}"
      command: lxc copy ubuntu {{ item }}
      register: lxc_clone

    - name: Start cloned LXC containers
      loop: "{{ container_names }}"
      command: lxc start {{ item }}
      register: lxc_start

    - name: Wait for the containers to be up
      shell: |
        until lxc list {{ item }} | grep -q RUNNING; do
          sleep 1
        done
      retries: 10
      delay: 5
      loop: "{{ container_names }}"
      register: wait_result
      until: wait_result.rc == 0
      ignore_errors: yes

    - name: Ensure the containers are running
      command: lxc list
      register: lxc_list

    - debug:
        msg: "Cloned LXC containers are launched and running: {{ lxc_list.stdout }}"
